### ISSUE TITLE
SqliteException: SQLite Error 1: 'no such table: InventoryItemEvents'.

### ISSUE THREAD

**Issue by clarkz** [tedbouskill/m-r-core-of#11]

**Comment by clarkz** [comment]
Error while adding a new inventory item

**Comment by tedbouskill** [comment]
I can't reproduce this.  It automatically creates the DB for me including the schema.  In production the DB would already exist.

**Comment by tedbouskill** [comment]
Apparently, EF can't create a new DB using code models in two different contexts which is what I was attempting.  I had to create a new DbContext that created both models, to then use two different contexts in the code to simulate two different data stores.
